In [1]:
#Lets analyze the data before diving into the dashboard building part

In [2]:
import pandas as pd

In [3]:
shots = pd.read_csv("C:\\Users\\fhube\\Downloads\\2021 Python for Machine Learning Data Science Masterclass\\1.2\\UNZIP_FOR_NOTEBOOKS_FINAL\\Shoot Model\\NBA Shot Locations 1997 - 2020.csv")

In [4]:
shots.head()

,Game ID,Game Event ID,Player ID,Player Name,Team ID,Team Name,Period,Minutes Remaining,Seconds Remaining,Action Type,...,Shot Zone Area,Shot Zone Range,Shot Distance,X Location,Y Location,Shot Made Flag,Game Date,Home Team,Away Team,Season Type
0,29700427,389,100,Tim Legler,1610612764,Washington Wizards,4,11,22,Jump Shot,...,Right Side(R),8-16 ft.,15,117,109,1,19980102,WAS,IND,Regular Season
1,29700427,406,100,Tim Legler,1610612764,Washington Wizards,4,9,36,Jump Shot,...,Right Side(R),8-16 ft.,14,143,25,0,19980102,WAS,IND,Regular Season
2,29700427,475,100,Tim Legler,1610612764,Washington Wizards,4,3,7,Jump Shot,...,Left Side(L),8-16 ft.,10,-87,55,0,19980102,WAS,IND,Regular Season
3,29700427,487,100,Tim Legler,1610612764,Washington Wizards,4,1,45,Jump Shot,...,Center(C),Less Than 8 ft.,5,-1,53,0,19980102,WAS,IND,Regular Season
4,29700427,497,100,Tim Legler,1610612764,Washington Wizards,4,0,45,Jump Shot,...,Right Side(R),8-16 ft.,14,89,113,0,19980102,WAS,IND,Regular Season

In [5]:
shots.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4729512 entries, 0 to 4729511
Data columns (total 22 columns):
 #   Column             Dtype
---  ------             -----
 0   Game ID            int64
 1   Game Event ID      int64
 2   Player ID          int64
 3   Player Name        object
 4   Team ID            int64
 5   Team Name          object
 6   Period             int64
 7   Minutes Remaining  int64
 8   Seconds Remaining  int64
 9   Action Type        object
 10  Shot Type          object
 11  Shot Zone Basic    object
 12  Shot Zone Area     object
 13  Shot Zone Range    object
 14  Shot Distance      int64
 15  X Location         int64
 16  Y Location         int64
 17  Shot Made Flag     int64
 18  Game Date          int64
 19  Home Team          object
 20  Away Team          object
 21  Season Type        object
dtypes: int64(12), object(10)
memory usage: 793.8+ MB

In [6]:
shots.describe()

,Game ID,Game Event ID,Player ID,Team ID,Period,Minutes Remaining,Seconds Remaining,Shot Distance,X Location,Y Location,Shot Made Flag,Game Date
count,4.729512e+06,4.729512e+06,4.729512e+06,4.729512e+06,4.729512e+06,4.729512e+06,4.729512e+06,4.729512e+06,4.729512e+06,4.729512e+06,4.729512e+06,4.729512e+06
mean,2.314379e+07,2.501681e+02,1.639145e+05,1.610613e+09,2.477790e+00,5.332437e+00,2.873821e+01,1.208963e+01,-1.316958e+00,7.634400e+01,4.517832e-01,2.008996e+07
std,5.521124e+06,1.589274e+02,3.733497e+05,8.595674e+00,1.139482e+00,3.468664e+00,1.745678e+01,9.850088e+00,1.100864e+02,8.703236e+01,4.976698e-01,6.512593e+04
min,2.000000e+07,1.000000e+00,3.000000e+00,1.610613e+09,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-2.500000e+02,-5.200000e+01,0.000000e+00,1.997103e+07
25%,2.060015e+07,1.130000e+02,1.515000e+03,1.610613e+09,1.000000e+00,2.000000e+00,1.400000e+01,2.000000e+00,-6.000000e+01,3.000000e+00,0.000000e+00,2.003120e+07
50%,2.120030e+07,2.450000e+02,2.550000e+03,1.610613e+09,2.000000e+00,5.000000e+00,2.900000e+01,1.300000e+01,0.000000e+00,3.800000e+01,0.000000e+00,2.009033e+07
75%,2.170117e+07,3.750000e+02,2.019370e+05,1.610613e+09,3.000000e+00,8.000000e+00,4.400000e+01,2.100000e+01,5.600000e+01,1.450000e+02,1.000000e+00,2.015013e+07
max,4.990009e+07,1.012000e+03,1.629760e+06,1.610613e+09,8.000000e+00,1.200000e+01,5.900000e+01,8.900000e+01,2.500000e+02,8.840000e+02,1.000000e+00,2.020031e+07

In [7]:
shots.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Game ID,4729512.0,2.314379e+07,5.521124e+06,2.000000e+07,2.060015e+07,2.120030e+07,2.170117e+07,4.990009e+07
Game Event ID,4729512.0,2.501681e+02,1.589274e+02,1.000000e+00,1.130000e+02,2.450000e+02,3.750000e+02,1.012000e+03
Player ID,4729512.0,1.639145e+05,3.733497e+05,3.000000e+00,1.515000e+03,2.550000e+03,2.019370e+05,1.629760e+06
Team ID,4729512.0,1.610613e+09,8.595674e+00,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09,1.610613e+09
Period,4729512.0,2.477790e+00,1.139482e+00,1.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,8.000000e+00
Minutes Remaining,4729512.0,5.332437e+00,3.468664e+00,0.000000e+00,2.000000e+00,5.000000e+00,8.000000e+00,1.200000e+01
Seconds Remaining,4729512.0,2.873821e+01,1.745678e+01,0.000000e+00,1.400000e+01,2.900000e+01,4.400000e+01,5.900000e+01
Shot Distance,4729512.0,1.208963e+01,9.850088e+00,0.000000e+00,2.000000e+00,1.300000e+01,2.100000e+01,8.900000e+01
X Location,4729512.0,-1.316958e+00,1.100864e+02,-2.500000e+02,-6.000000e+01,0.000000e+00,5.600000e+01,2.500000e+02
Y Location,4729512.0,7.634400e+01,8.703236e+01,-5.200000e+01,3.000000e+00,3.800000e+01,1.450000e+02,8.840000e+02
Shot Made Flag,4729512.0,4.517832e-01,4.976698e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
Game Date,4729512.0,2.008996e+07,6.512593e+04,1.997103e+07,2.003120e+07,2.009033e+07,2.015013e+07,2.020031e+07

In [8]:
shots.sort_values('Shot Distance')

,Game ID,Game Event ID,Player ID,Player Name,Team ID,Team Name,Period,Minutes Remaining,Seconds Remaining,Action Type,...,Shot Zone Area,Shot Zone Range,Shot Distance,X Location,Y Location,Shot Made Flag,Game Date,Home Team,Away Team,Season Type
2055929,20800338,332,101109,Raymond Felton,1610612766,Charlotte Bobcats,3,0,32,Layup Shot,...,Center(C),Less Than 8 ft.,0,0,0,1,20081213,CHA,DET,Regular Season
3981545,21701011,59,203076,Anthony Davis,1610612740,New Orleans Pelicans,1,6,53,Layup Shot,...,Center(C),Less Than 8 ft.,0,-6,6,1,20180313,NOP,CHA,Regular Season
593936,20000514,25,238,Tyrone Hill,1610612755,Philadelphia 76ers,1,8,37,Slam Dunk Shot,...,Center(C),Less Than 8 ft.,0,3,4,1,20010112,WAS,PHI,Regular Season
1475758,20500579,148,101158,Orien Greene,1610612738,Boston Celtics,2,7,28,Tip Shot,...,Center(C),Less Than 8 ft.,0,0,0,0,20060121,NJN,BOS,Regular Season
1475757,20500579,146,101158,Orien Greene,1610612738,Boston Celtics,2,7,30,Layup Shot,...,Center(C),Less Than 8 ft.,0,0,0,0,20060121,NJN,BOS,Regular Season
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1010112,20200571,225,304,John Stockton,1610612762,Utah Jazz,2,0,0,Jump Shot,...,Back Court(BC),Back Court Shot,88,23,881,0,20030118,UTA,CLE,Regular Season
2790464,21100969,91,255,Grant Hill,1610612756,Phoenix Suns,1,0,0,Jump Shot,...,Back Court(BC),Back Court Shot,89,166,877,0,20120424,UTA,PHX,Regular Season
1773627,20601202,244,2404,Chris Wilcox,1610612760,Seattle SuperSonics,2,0,0,Jump Shot,...,Back Court(BC),Back Court Shot,89,-161,876,0,20070415,LAL,SEA,Regular Season
1389912,20400314,457,2549,Chris Kaman,1610612746,Los Angeles Clippers,4,0,0,Jump Shot,...,Back Court(BC),Back Court Shot,89,200,876,0,20041214,UTA,LAC,Regular Season
2624876,21000435,132,2581,Steve Blake,1610612747,Los Angeles Lakers,1,0,0,Jump Shot,...,Back Court(BC),Back Court Shot,89,-164,884,0,20101225,LAL,MIA,Regular Season

In [9]:
shots.corr()

,Game ID,Game Event ID,Player ID,Team ID,Period,Minutes Remaining,Seconds Remaining,Shot Distance,X Location,Y Location,Shot Made Flag,Game Date
Game ID,1.000000,-0.012543,-0.062916,-0.002681,-0.001979,0.000004,-0.000576,-0.008207,-0.002050,-0.014602,-0.005117,-0.199343
Game Event ID,-0.012543,1.000000,0.141287,-0.009316,0.934033,-0.252865,-0.020889,0.044887,0.000586,0.053370,-0.018967,0.158031
Player ID,-0.062916,0.141287,1.000000,-0.004986,0.017719,-0.003752,0.000959,0.017473,0.001564,0.049995,0.001608,0.511525
Team ID,-0.002681,-0.009316,-0.004986,1.000000,0.000696,-0.000554,-0.000507,-0.010092,-0.001272,-0.013924,0.000890,-0.015235
Period,-0.001979,0.934033,0.017719,0.000696,1.000000,-0.027226,0.000616,0.029715,-0.000539,0.025293,-0.018169,0.004505
Minutes Remaining,0.000004,-0.252865,-0.003752,-0.000554,-0.027226,1.000000,0.009387,-0.038310,-0.001666,-0.043925,0.015978,-0.000078
Seconds Remaining,-0.000576,-0.020889,0.000959,-0.000507,0.000616,0.009387,1.000000,-0.036701,-0.000921,-0.041890,0.015933,0.002229
Shot Distance,-0.008207,0.044887,0.017473,-0.010092,0.029715,-0.038310,-0.036701,1.000000,-0.011995,0.772259,-0.189225,0.058400
X Location,-0.002050,0.000586,0.001564,-0.001272,-0.000539,-0.001666,-0.000921,-0.011995,1.000000,0.013780,0.003118,0.005745
Y Location,-0.014602,0.053370,0.049995,-0.013924,0.025293,-0.043925,-0.041890,0.772259,0.013780,1.000000,-0.145013,0.105797
Shot Made Flag,-0.005117,-0.018967,0.001608,0.000890,-0.018169,0.015978,0.015933,-0.189225,0.003118,-0.145013,1.000000,0.009467
Game Date,-0.199343,0.158031,0.511525,-0.015235,0.004505,-0.000078,0.002229,0.058400,0.005745,0.105797,0.009467,1.000000

In [10]:
shots[['X Location','Y Location']].corr()

            X Location  Y Location
X Location     1.00000     0.01378
Y Location     0.01378     1.00000

In [11]:
shots['X Location'].min()

-250

In [12]:
shots['Y Location'].min()

-52

In [13]:
shots['X Location'].max()

250

In [14]:
shots['Y Location'].max()

884

In [15]:
shots['Shot Made Flag'].value_counts()

0    2592798
1    2136714
Name: Shot Made Flag, dtype: int64

In [16]:
shots['Team Name'].unique()

array(['Washington Wizards', 'Utah Jazz', 'San Antonio Spurs',
       'Atlanta Hawks', 'Toronto Raptors', 'Portland Trail Blazers',
       'New York Knicks', 'Houston Rockets', 'Phoenix Suns', 'Miami Heat',
       'Cleveland Cavaliers', 'Milwaukee Bucks', 'Los Angeles Clippers',
       'Philadelphia 76ers', 'Denver Nuggets', 'Golden State Warriors',
       'Orlando Magic', 'Dallas Mavericks', 'Seattle SuperSonics',
       'Sacramento Kings', 'Los Angeles Lakers', 'Vancouver Grizzlies',
       'Charlotte Hornets', 'New Jersey Nets', 'Chicago Bulls',
       'Indiana Pacers', 'Boston Celtics', 'Detroit Pistons',
       'Minnesota Timberwolves', 'Memphis Grizzlies',
       'New Orleans Hornets', 'Charlotte Bobcats',
       'New Orleans/Oklahoma City Hornets', 'Oklahoma City Thunder',
       'Brooklyn Nets', 'New Orleans Pelicans', 'LA Clippers'],
      dtype=object)

In [17]:
shots.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
4729507    False
4729508    False
4729509    False
4729510    False
4729511    False
Length: 4729512, dtype: bool

In [18]:
len(shots)

4729512

In [19]:
shots.isna().sum()

Game ID              0
Game Event ID        0
Player ID            0
Player Name          0
Team ID              0
Team Name            0
Period               0
Minutes Remaining    0
Seconds Remaining    0
Action Type          0
Shot Type            0
Shot Zone Basic      0
Shot Zone Area       0
Shot Zone Range      0
Shot Distance        0
X Location           0
Y Location           0
Shot Made Flag       0
Game Date            0
Home Team            0
Away Team            0
Season Type          0
dtype: int64

In [20]:
shots['Team Name'].value_counts()[:10]

#teams with the most shots

Los Angeles Lakers       169375
San Antonio Spurs        168651
Golden State Warriors    167564
Dallas Mavericks         163846
Boston Celtics           163755
Indiana Pacers           161985
Phoenix Suns             161001
Cleveland Cavaliers      160943
Detroit Pistons          159842
Chicago Bulls            159383
Name: Team Name, dtype: int64

In [21]:
shots['Player Name'].value_counts()[:10]

Kobe Bryant        30220
LeBron James       29658
Dirk Nowitzki      26376
Tim Duncan         24221
Vince Carter       22677
Carmelo Anthony    22526
Paul Pierce        21877
Kevin Garnett      21472
Dwyane Wade        20677
Allen Iverson      20284
Name: Player Name, dtype: int64

In [22]:
Manu = shots.loc[shots['Player Name'].str.contains("Ginobili",case=False)]

In [23]:
Manu

,Game ID,Game Event ID,Player ID,Player Name,Team ID,Team Name,Period,Minutes Remaining,Seconds Remaining,Action Type,...,Shot Zone Area,Shot Zone Range,Shot Distance,X Location,Y Location,Shot Made Flag,Game Date,Home Team,Away Team,Season Type
951482,20200003,119,1938,Manu Ginobili,1610612759,San Antonio Spurs,1,0,58,Jump Shot,...,Right Side Center(RC),24+ ft.,25,110,227,1,20021029,LAL,SAS,Regular Season
951483,20200003,125,1938,Manu Ginobili,1610612759,San Antonio Spurs,1,0,0,Jump Shot,...,Right Side(R),24+ ft.,22,225,35,0,20021029,LAL,SAS,Regular Season
951484,20200003,133,1938,Manu Ginobili,1610612759,San Antonio Spurs,2,11,27,Reverse Layup Shot,...,Center(C),Less Than 8 ft.,0,0,0,0,20021029,LAL,SAS,Regular Season
951485,20200003,410,1938,Manu Ginobili,1610612759,San Antonio Spurs,4,11,44,Jump Shot,...,Left Side Center(LC),24+ ft.,24,-169,184,0,20021029,LAL,SAS,Regular Season
951486,20200003,439,1938,Manu Ginobili,1610612759,San Antonio Spurs,4,9,7,Slam Dunk Shot,...,Center(C),Less Than 8 ft.,0,0,0,1,20021029,LAL,SAS,Regular Season
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4704459,41700155,295,1938,Manu Ginobili,1610612759,San Antonio Spurs,2,1,25,Jump Shot,...,Right Side(R),24+ ft.,23,231,22,0,20180424,GSW,SAS,Playoffs
4704460,41700155,307,1938,Manu Ginobili,1610612759,San Antonio Spurs,2,0,31,Jump Shot,...,Left Side Center(LC),24+ ft.,28,-159,231,0,20180424,GSW,SAS,Playoffs
4704461,41700155,445,1938,Manu Ginobili,1610612759,San Antonio Spurs,3,2,10,Driving Floating Jump Shot,...,Center(C),8-16 ft.,11,5,111,1,20180424,GSW,SAS,Playoffs
4704462,41700155,467,1938,Manu Ginobili,1610612759,San Antonio Spurs,3,0,33,Driving Layup Shot,...,Center(C),Less Than 8 ft.,1,9,8,1,20180424,GSW,SAS,Playoffs
4704463,41700155,568,1938,Manu Ginobili,1610612759,San Antonio Spurs,4,4,23,Driving Finger Roll Layup Shot,...,Center(C),Less Than 8 ft.,6,-55,35,0,20180424,GSW,SAS,Playoffs

In [24]:
len(Manu)

12468

In [25]:
Manu.describe()

,Game ID,Game Event ID,Player ID,Team ID,Period,Minutes Remaining,Seconds Remaining,Shot Distance,X Location,Y Location,Shot Made Flag,Game Date
count,1.246800e+04,12468.000000,12468.0,1.246800e+04,12468.000000,12468.000000,12468.000000,12468.000000,12468.000000,12468.000000,12468.000000,1.246800e+04
mean,2.442137e+07,240.991578,1938.0,1.610613e+09,2.469442,4.818014,28.185274,13.580687,3.990616,88.151588,0.444257,2.009512e+07
std,7.622129e+06,141.982037,0.0,0.000000e+00,1.125243,3.734276,17.676436,10.685879,120.714844,94.089877,0.496903,4.272103e+04
min,2.020000e+07,2.000000,1938.0,1.610613e+09,1.000000,0.000000,0.000000,0.000000,-246.000000,-36.000000,0.000000,2.002103e+07
25%,2.060068e+07,114.000000,1938.0,1.610613e+09,1.000000,1.000000,13.000000,2.000000,-57.000000,7.000000,0.000000,2.006040e+07
50%,2.100043e+07,235.000000,1938.0,1.610613e+09,2.000000,4.000000,29.000000,15.000000,0.000000,46.000000,0.000000,2.009111e+07
75%,2.150120e+07,356.000000,1938.0,1.610613e+09,3.000000,8.000000,43.000000,24.000000,84.000000,170.000000,1.000000,2.013051e+07
max,4.170016e+07,808.000000,1938.0,1.610613e+09,7.000000,12.000000,59.000000,86.000000,248.000000,841.000000,1.000000,2.018042e+07

In [26]:
shots['Period'].unique()

array([4, 1, 2, 3, 5, 6, 7, 8], dtype=int64)

In [28]:
shots['Period'].value_counts()

#we need to transform the data and put that the period 5,6,7 and 8 are OT
#necesitamos transformar la data y poner que el period 5,6,7 y 8 son OT

1    1241342
2    1179133
3    1157160
4    1117611
5      29324
6       4115
7        720
8        107
Name: Period, dtype: int64

In [35]:
shots['Game Date'].max()

20200311

In [34]:
shots['Game Date'].min()

19971031